title: python for climate scientists
minimal_mistakes_skin: "contrast" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
remote_theme: "bairdlangenbrunner/minimal-mistakes"
