title: Python for climate scientists
minimal_mistakes_skin: "baird" #"default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum" "sunrise"
remote_theme: "bairdlangenbrunner/swiss"
theme_color: solarized-orange

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      #author_profile: true
      #read_time: true
      comments: true
      share: true
      related: true

include:
  - _pages
