title: Python for climate scientists

remote_theme: "bairdlangenbrunner/swiss"

theme_color: green-light
syntax_highlighting: light
gradient_header: false

author: Baird
email: blangenb@uci.edu
github_username:  bairdlangenbrunner
github_repo: swiss-cheese
timezone: America/Los_Angeles

plugins:
  - jekyll-feed
  - jemoji

# notes:
# if you include _coding here, and publish with --drafts,
# then the _coding/_drafts collection gets published
# and they are included in the html front page layout because
# they apparently count as posts?
include:
#  - _posts
  - _coding
  - _conda
  - _pages

collections:
  - coding
#  - pages
#  - posts

collections:
  coding:
    output: true
  conda:
    output: true
#    permalink: python-for-climate-scientists/:collection/:path
  pages:
    output: true
#    permalink: /:name
  pages:
    output: true

defaults:
  - scope:
      path: ""
      type: coding
    values:
      layout: post-no-date
  - scope:
      path: ""
      type: conda
    values:
      layout: post-no-date
  - scope:
      path: ""
      type: posts
    values:
      layout: post-no-date
  - scope:
      path: ""
      type: pages
    values:
      layout: page

collections_dir: collections

# Build settings
markdown: kramdown
highlighter: rouge
