title: Python for climate scientists
remote_theme: "bairdlangenbrunner/swiss"
theme_color: solarized-teal

author: Baird
email: blangenb@uci.edu

plugins:
  - jekyll-feed
  - jemoji

include:
  - _pages

collections:
  - coding

collections:
  coding:
    output: true
    permalink: /:collection/:name

defaults:
  - scope:
      path: ""
      type: coding
    values:
      layout: page

collections_dir: collections
