title: Python for climate scientists
remote_theme: "bairdlangenbrunner/swiss"
theme_color: solarized-teal

author: Baird
email: blangenb@uci.edu

plugins:
  - jekyll-feed
  - jemoji

include:
  - _pages